# Generated by Django 3.1.3 on 2020-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201111_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.FileField(null=True, upload_to='videos/%y'),
        ),
    ]
