# Generated by Django 3.1.3 on 2020-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201111_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='videos/%y'),
        ),
    ]
